---
- hosts: all
  become: true
  tasks:

  - name: remove apache and php packages ubuntu
    ansible.builtin.package:
      name: 
        - "{{ apache_package }}"
        - "{{ php_package }}"
      state: absent
