---
    - name: install apache on web servers
      tags: apache, ubuntu
      ansible.builtin.apt:
        name:
          - apache2
          - libapache2-mod-php

    - name: copy html file
      tags: apache, ubuntu
      ansible.builtin.copy:
        src: default_site.html
        dest: /var/www/html/index.htm
        owner: root
        group: root
        mode: 0644
